# Node.js CI workflow

# build: base href is set in the build-ci script

name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IS_PUSH_MASTER: ${{ github.ref == 'refs/heads/master' }}
      IS_PUSH_TAG: ${{ startsWith(github.ref, 'refs/tags/') }}
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: Run lint
      run: yarn run lint
    - name: Run tests
      run: yarn run test-ci
    - name: Build
      run: |
        if ${{env.IS_PUSH_TAG}}; then
          yarn run build-stable
        else
          yarn run build-ci
        fi
    - name: Push to gh-pages (if tag or master branch)
      if: env.IS_PUSH_MASTER == 'true' || env.IS_PUSH_TAG == 'true'
      run: |
        git config user.email github-actions@github.com
        git config user.name github-actions
        git checkout gh-pages
        if ${{env.IS_PUSH_MASTER}}; then
          rm -Rf ./demo/trunk/*
          cp -Rf ./dist/dwv-angular/* ./demo/trunk
          git add ./demo/trunk/*
        else
          rm -Rf ./demo/stable/*
          cp -Rf ./dist/dwv-angular/* ./demo/stable
          git add ./demo/stable/*
        fi
        git diff-index --quiet HEAD || git commit -m "CI run ${{ github.run_number }} pushed to gh-pages"
        git push -fq origin gh-pages
